services:
  - type: web
    name: budgetiq-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ARCJET_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: https://ayush-agrawal-lab.github.io
    autoDeploy: true